### ISSUE TITLE
C209 Tag doesn't work :(

### ISSUE THREAD

**Issue by kmsmile2** [u-blox/c209-aoa-tag#1]
Hi, this is Michael.
Now I want to use C209 aoa tag, but it doesn't work.
I want to build and flash it.
However, I can't. :(
I uploaded the post 10days ago, no one answered.

https://portal.u-blox.com/s/question/0D52p0000BOI7UxCQL/xplraoa-explorer-kits-c209-tags-software-and-flashing

I don't have a bad intention.
Is there anybody who can help tag work?
Please help me!

**Comment by kmsmile2** [comment]
When I builded with command line (nRF Connect SDK v1.5.0 and Open bash'. there was a problem with building.
Actually, I didn't know where the project is.
That's why I did like this.
(Path: ~/c209-aoa-tag-master/u-blox-sho-OpenCPU/zephyr/boards/arm/ubx_evkninab4_nrf52833)

![Screenshot 2021-09-23 165224](https://user-images.githubusercontent.com/59598874/134472048-f6dd088b-0554-4ae9-9e7b-b6fc8332dc55.jpg)

What was the problem?

**Comment by jakkra** [comment]
Hi, the **root** folder is the cloned repository at the top level, so I think that is why you have problems building. When running `west build -b ubx_evkninab4_nrf52833` you need to be in the folder `c209-aoa-tag-master` in your case.

Also if you don't want to compile you can download pre-compiled FW here: https://github.com/u-blox/c209-aoa-tag/releases

Also if you want to do a clean re-build you can use this argument: https://docs.zephyrproject.org/latest/guides/west/build-flash-debug.html#pristine-builds

**Comment by kmsmile2** [comment]
Thank you so much, jakkra.
Thanks to your help, I could go one step more.
I changed my root folder from wrong folder to 'c209-aoa-tag'.
'west build -b ubx_evkninab4_nrf52833' command works well.

But, 'west flash' doesn't work like this photo.
(I'm sure that c209 board was connected to my desktop by using USB port)

![image](https://user-images.githubusercontent.com/59598874/134617673-d036f58e-22d5-412d-82ae-b1fac200ae29.png)

Therefore, I chose the second method 'Download pre-compiled FW'.
When I ran this command 'nrfutil dfu serial -pkg app.zip -p COM8 115200 -fc 1', there was error.
(My usb serial port number was 8.) 

![image](https://user-images.githubusercontent.com/59598874/134617841-3ee43ea0-f12d-4fa2-a657-fcb6206cab17.png)


Is there any solution?
I'm sorry to bother you.

**Comment by perssonmagnus** [comment]
Hi,
It could be that you have this port open in another program, like a terminal emulator or similar?

**Comment by kmsmile2** [comment]
Thank you for your fast response.
I checked it one more time, and all program was closed.

![image](https://user-images.githubusercontent.com/59598874/134625794-d04642e4-8da5-4e1f-b1bd-cde411c1b913.png)

If I connect the other board like **nrf52840-DK**, command 'pyocd list' worked and it showed me the information of the board.
However, I didn't know the information of this tag if I connected it to desktop.

![image](https://user-images.githubusercontent.com/59598874/134625761-7d9f0944-5374-41b8-b458-73a96582a36f.png)

In my case, it was hard to flash by using usb cable, I used 10-pins debugger port.
I think it works, now.

If you are okay, could you let me know how to flash by using usb port instead of 10-pin debugger port?

Thank you so much.

**Comment by kmsmile2** [comment]
Could I ask one more thing?
I flashed the c209 tag as I told you, and then I checked that c211's array led were blinky.
That's why I thought that the tag and anchor node works very well.
Also, I checked the Anchor node's response when I put the Anchor node AT commands  by using 's-center'.
**However, when I put the c209 AT command by using 's-center', there is no response like 'OK' or 'Error'**
**For example, I want to change the power of tx (c209 tag) therefore I put the AT command ('AT+TXPWR=0'), but no answer!**

![image](https://user-images.githubusercontent.com/59598874/134634651-66ad6dae-a162-4dba-be19-5697c0badab8.png)


![image](https://user-images.githubusercontent.com/59598874/134634838-4523876c-2c99-46de-8ca8-bf07f86332d1.png)


I'm not sure, but I guess that two situation (1. USB port doesn't work when I flashed the c209 tag, 2. c209 tag AT command doesn't work)  came from same excuse, doesn't it?

**Comment by jakkra** [comment]
There should be no flow control when sending AT commands to the C209 tag. Also AT interface is only availible for about 10 seconds after reset of the tag (to save battery) so you need to send AT to the C209 tag within 10s after reset, after any AT command sent the C209 tag will keep UART open for AT commands.

Edit: since you compile the code yourself you can also just put 0 here as the tx power if you cannot get the AT interface to work
https://github.com/u-blox/c209-aoa-tag/blob/master/src/main.c#L123

**Comment by jakkra** [comment]
For your problem with flashing using `nrfutil`:
- First you need to re-flash the bootloader as you probably overwrite it when flashing the application using the debugger. It's on the start of this section how to do it: (https://github.com/u-blox/c209-aoa-tag#building-the-application-to-use-with-opencpu-dfu-bootloader) 
- Then when bootloader is flashed you will be able to again flash the pre-compiled application found under releases.
- Looking at the error message you got from `nrfutil`I still think the COM port was already opened in Windows due to "access denied" for COM8. So double check one more time in device manager that the C209 tag really has COM8 and also make sure no program has the port opened.

**Comment by kmsmile2** [comment]
Thank you for fast response.
I checked that c209 tag AT command works very well! :)

And I will follow your advice, and I will let you know if there is progress.
Thank you soooo much! :)

**Comment by jakkra** [comment]
I'll close this issue as it seems like you got it working, feel free to re-open if there still is a problem.
