### ISSUE TITLE
how do you flash the C209? 

### ISSUE THREAD

**Issue by sdetweil** [u-blox/c209-aoa-tag#6]
I am using a mac.  don't have a windows machine

seeger IDE, build is successful...

download shows not connected.
jlink says no emulator connected via USB

tag is connected via usb
assume flash is similar  to process on arduino..

identify port, link to something
select the tool to download/flash

i see the port in the arduino IDE  so I iknow its being created

**Comment by jakkra** [comment]
Hi, there are two ways to flash the C209. Either use the pre-flashed bootloader that is flashed to the C209 or by SWD. The reason jlink does not find the C209 is because the C209 has no debugger chip, hence you need an external j-link debugger. 
1. If you just need to flash once then I recommend flashing the pre-built binary that can be found under "[Releases](https://github.com/u-blox/c209-aoa-tag/releases)" using the pre flashed bootloader. Instructions in chapter [3.4.2.1 here](https://www.u-blox.com/en/ubx-viewer/view/XPLR-AOA-Explorer-kits_UserGuide_UBX-21004616?url=https%3A%2F%2Fwww.u-blox.com%2Fsites%2Fdefault%2Ffiles%2FXPLR-AOA-Explorer-kits_UserGuide_UBX-21004616.pdf)
2. If you intend to develop SW for the C209, then an external programmer is needed (you _CAN_ [follow those steps also](https://github.com/u-blox/c209-aoa-tag#building-the-application-to-use-with-opencpu-dfu-bootloader), but iterations will be slower as flashing using DFU bootloader is much slower then using SWD).

**Comment by sdetweil** [comment]
thanks.. a couple words missing in the doc

c209 
```
Press the SW2 button on the C209(while resetting the board) 
```

but nothing says how to reset the 209..

button 1 on the 211 is reset.. is it the same on the 209? 

also, in the referenced doc, flashing the c211
```
As  there  is  no  software  to  boot  during  the  initial  startup,  the NINA-B411 module automatically enters the software download mode. **For coming updates of NINA-B41** u-connectLocate software the bootloader must be  manually  set  in software download  mode  by  pressing  the  SW2  button while resetting the board
```

so, which is it for the current 211?    what does 'coming updates' mean? relative to when?

rereading the words does that mean, 

when there are updates to the u-connectLocate software, to apply them to the C211 after the  first version is installed, you will have to set bootloader mode manually by.....

**Comment by jakkra** [comment]
Hi, thanks for the input. 

> but nothing says how to reset the 209..
button 1 on the 211 is reset.. is it the same on the 209?

SW1 is reset on the C209, that could probably be a bit more clear in the documnetation. C209 is reset by clicking SW1.
![Capture_tag_btn](https://user-images.githubusercontent.com/4318648/150818085-65442d16-48ac-433c-8fb6-e4572ef1a7fd.PNG)

> so, which is it for the current 211? what does 'coming updates' mean? relative to when?

With 'coming updates' it's referred to the next time you update the SW, as next time the application will be booted automatically by bootloader (since there is one flashed), hence you are requried to enter the bootloader in order to upload SW to the C211, either by `AT+UFWUPD` command or using the buttons as described.

So yes the way you rephrased it is correct. 

@perssonmagnus maybe there could be some clarification in the documentation, especially in regards to that SW1 is the RESET button on C209.

**Comment by sdetweil** [comment]
thx.. working... one more thing

doesn't say the flashing blue light is advertising

and 
```
4.2.2Enabling/disabling advertising  Press and hold the C209 button
```

maybe 
```
4.2.2 Enabling/disabling advertising Press and hold the C209 SW2 button
```
and  add
``
the light will not change until u release the SW2 button
```

**Comment by perssonmagnus** [comment]
@jakkra yes, figure 13 in the XPLR-AOA-kits user guide can be updated to reflect the reset button. 

Note that Figure 12 indicates a reset button, and that 'reset' also can indicate powering on/off.

**Comment by sdetweil** [comment]
@perssonmagnus  thanks.. skipped fig 12 as it wasn't helpful to the flashing task at hand

and didn't connect 'switches' with the SW? on the outside of the case.
(what it has and what is exposed to the user are many times different, 40 yrs doing this stuff and there are always surprises)

**Comment by perssonmagnus** [comment]
Great, I think we can close this now and I'll make sure the doc is updated.
