### ISSUE TITLE
timing and control BT advertising

### ISSUE THREAD

**Issue by sdetweil** [u-blox/c209-aoa-tag#8]
I want to set the eddystone info from an AT command over serial port.  (see #7)

adding an AT command for the info is easy
(and for start/stop advertising as discussed before) 

Are there any issues/dependencies doing bt_enable later than the current design?   and from the AT commandHandler  

some platforms get the co-processor running and you have to do other calls to change the bt setup before changing/setting the advertising packet info

**Comment by jakkra** [comment]
Hi, I think you can find that info [here ](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/reference/bluetooth/gap.html?highlight=bt_enable#c.bt_enable) or somewhere else in the nRF Connect documentation. 

I don't see any problem calling `bt_enable` later. Only problem I can think of is that for example buttons are clicked, then there may be a crash, since BT is not started yet and buttons change adv. interval, but that can be fixed by moving `buttonsInit` to the `btReadyCb` callback.

**Comment by sdetweil** [comment]
great! thanks
